name: 'Build'
on: [pull_request, push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcc9 g++9
      run: sh updatecompilers.sh
    - name: Export compilers
      run: export CXX="g++-9" CC="gcc-9" 
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Install gcovr
      run: sudo apt-get install python3-setuptools && sudo pip3 install git+https://github.com/gcovr/gcovr.git
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
    - name: Run Linter
      run: cd src && cppcheck *.cpp && cd ..
    - name: Configure
      run: sh configure.sh
    - name: Work
      run: cd build/ && ./Lemmatizator && cd ..
    - name: Test
      run: cp -rf postfixes/ build/ && cd build/ && make coverage && ctest && rm -rf postfixes
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: build/coverage/index.html
